name: Deploy

on:
 workflow_call:


jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: clone the code
        uses: actions/checkout@v7 
        
      - name: deploy throw nginx
        run: cp index.html /var/www/html
        
      - name: Deploy  the code
        run: echo "Code build using EC2 instance"
         -   echo "Deploy the code successfully "
   
